<?php

namespace Svr\Core\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class table_data_system_modules_actions extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('system.system_modules_actions')->truncate();

        DB::table('system.system_modules_actions')->insert([
            [
                "right_id" => "1",
                "module_slug" => "users",
                "right_action" => "list",
                "right_name" => "Список         пользователей",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-05-22 14:10:17.445764",
                "right_log_write" => "disabled",
            ],
            [
                "right_id" => "2",
                "module_slug" => "users",
                "right_action" => "data",
                "right_name" => "Данные         пользователя",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-05-22 14:10:17.445764",
                "right_log_write" => "disabled",
            ],
            [
                "right_id" => "8",
                "module_slug" => "users",
                "right_action" => "roles_list",
                "right_name" => "Список         ролей           пользователя",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-05-22 14:10:17.445764",
                "right_log_write" => "disabled",
            ],
            [
                "right_id" => "13",
                "module_slug" => "users",
                "right_action" => "avatar_add",
                "right_name" => "Обновление     аватара",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-05-22 14:10:17.445764",
                "right_log_write" => "disabled",
            ],
            [
                "right_id" => "14",
                "module_slug" => "users",
                "right_action" => "avatar_delete",
                "right_name" => "Удаление     аватара",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-05-22 14:10:17.445764",
                "right_log_write" => "disabled",
            ],
            [
                "right_id" => "19",
                "module_slug" => "users",
                "right_action" => "forgot_password",
                "right_name" => "Восстановление пароля пользователя",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-05-22 14:10:17.445764",
                "right_log_write" => "disabled",
            ],
            [
                "right_id" => "20",
                "module_slug" => "roles",
                "right_action" => "list",
                "right_name" => "Список         ролей",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-05-22 14:10:17.445764",
                "right_log_write" => "disabled",
            ],
            [
                "right_id" => "21",
                "module_slug" => "roles",
                "right_action" => "data",
                "right_name" => "Данные         роли",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-05-22 14:10:17.445764",
                "right_log_write" => "disabled",
            ],
            [
                "right_id" => "26",
                "module_slug" => "roles",
                "right_action" => "rights_list",
                "right_name" => "Список         всех            прав",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-05-22 14:10:17.445764",
                "right_log_write" => "disabled",
            ],
            [
                "right_id" => "29",
                "module_slug" => "auth",
                "right_action" => "login",
                "right_name" => "Авторизация",
                "right_slug" => "public",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-05-22 14:10:17.445764",
                "right_log_write" => "disabled",
            ],
            [
                "right_id" => "30",
                "module_slug" => "auth",
                "right_action" => "logout",
                "right_name" => "Выход",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-05-22 14:10:17.445764",
                "right_log_write" => "disabled",
            ],
            [
                "right_id" => "31",
                "module_slug" => "auth",
                "right_action" => "info",
                "right_name" => "Информация     о               себе",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-05-22 14:10:17.445764",
                "right_log_write" => "disabled",
            ],
            [
                "right_id" => "32",
                "module_slug" => "auth",
                "right_action" => "set",
                "right_name" => "Установка      хозяйства",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-05-22 14:10:17.445764",
                "right_log_write" => "disabled",
            ],
            [
                "right_id" => "35",
                "module_slug" => "auth",
                "right_action" => "herriot_requisites",
                "right_name" => "Редактирование реквизитов хорриота",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-05-22 14:10:17.445764",
                "right_log_write" => "disabled",
            ],
            [
                "right_id" => "36",
                "module_slug" => "companies",
                "right_action" => "data",
                "right_name" => "Данные         хозяйства",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-05-22 14:10:17.445764",
                "right_log_write" => "disabled",
            ],
            [
                "right_id" => "43",
                "module_slug" => "companies",
                "right_action" => "list",
                "right_name" => "Список         хозяйств",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-05-22 14:10:17.445764",
                "right_log_write" => "disabled",
            ],
            [
                "right_id" => "44",
                "module_slug" => "companies",
                "right_action" => "locations_list",
                "right_name" => "Список         хозяйств",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-05-22 14:10:17.445764",
                "right_log_write" => "disabled",
            ],
            [
                "right_id" => "45",
                "module_slug" => "companies",
                "right_action" => "company_objects_list",
                "right_name" => "Список поднадзорных объектов",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-05-22 14:10:17.445764",
                "right_log_write" => "disabled",
            ],
            [
                "right_id" => "46",
                "module_slug" => "directories",
                "right_action" => "species",
                "right_name" => "Справочник видов животных",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-05-22 14:10:17.445764",
                "right_log_write" => "disabled",
            ],
            [
                "right_id" => "47",
                "module_slug" => "directories",
                "right_action" => "breeds",
                "right_name" => "Справочник пород животных",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-05-22 14:10:17.445764",
                "right_log_write" => "disabled",
            ],
            [
                "right_id" => "48",
                "module_slug" => "directories",
                "right_action" => "countries",
                "right_name" => "Справочник стран",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-05-22 14:10:17.445764",
                "right_log_write" => "disabled",
            ],
            [
                "right_id" => "49",
                "module_slug" => "directories",
                "right_action" => "regions",
                "right_name" => "Справочник регионов",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-05-22 14:10:17.445764",
                "right_log_write" => "disabled",
            ],
            [
                "right_id" => "50",
                "module_slug" => "directories",
                "right_action" => "districts",
                "right_name" => "Справочник районов",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-05-22 14:10:17.445764",
                "right_log_write" => "disabled",
            ],
            [
                "right_id" => "51",
                "module_slug" => "directories",
                "right_action" => "keeping_purposes",
                "right_name" => "Справочник целей содержания",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-05-22 14:10:17.445764",
                "right_log_write" => "disabled",
            ],
            [
                "right_id" => "52",
                "module_slug" => "directories",
                "right_action" => "keeping_types",
                "right_name" => "Справочник типов содержания",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-05-22 14:10:17.445764",
                "right_log_write" => "disabled",
            ],
            [
                "right_id" => "53",
                "module_slug" => "directories",
                "right_action" => "tools_locations",
                "right_name" => "Справочник мест нанесения маркировки",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-05-22 14:10:17.445764",
                "right_log_write" => "disabled",
            ],
            [
                "right_id" => "54",
                "module_slug" => "directories",
                "right_action" => "genders",
                "right_name" => "Справочник полов",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-05-22 14:10:17.445764",
                "right_log_write" => "disabled",
            ],
            [
                "right_id" => "55",
                "module_slug" => "directories",
                "right_action" => "out_basises",
                "right_name" => "Справочник оснований выбытия",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-05-22 14:10:17.445764",
                "right_log_write" => "disabled",
            ],
            [
                "right_id" => "56",
                "module_slug" => "directories",
                "right_action" => "out_types",
                "right_name" => "Справочник расходов выбытия",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-05-22 14:10:17.445764",
                "right_log_write" => "disabled",
            ],
            [
                "right_id" => "57",
                "module_slug" => "directories",
                "right_action" => "mark_statuses",
                "right_name" => "Справочник статусов маркирования",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-05-22 14:10:17.445764",
                "right_log_write" => "disabled",
            ],
            [
                "right_id" => "58",
                "module_slug" => "directories",
                "right_action" => "mark_tool_types",
                "right_name" => "Справочник типов средств маркирования",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-05-22 14:10:17.445764",
                "right_log_write" => "disabled",
            ],
            [
                "right_id" => "59",
                "module_slug" => "directories",
                "right_action" => "mark_types",
                "right_name" => "Справочник типов маркирования",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-05-22 14:10:17.445764",
                "right_log_write" => "disabled",
            ],
            [
                "right_id" => "60",
                "module_slug" => "notifications",
                "right_action" => "list",
                "right_name" => "Список уведомлений пользователя",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-05-22 14:10:17.445764",
                "right_log_write" => "disabled",
            ],
            [
                "right_id" => "61",
                "module_slug" => "notifications",
                "right_action" => "data",
                "right_name" => "Полная информация по уведомлению",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-05-22 14:10:17.445764",
                "right_log_write" => "disabled",
            ],
            [
                "right_id" => "62",
                "module_slug" => "notifications",
                "right_action" => "read_all",
                "right_name" => "Прочтение всех уведомлений",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-05-22 14:10:17.445764",
                "right_log_write" => "disabled",
            ],
            [
                "right_id" => "63",
                "module_slug" => "applications",
                "right_action" => "list",
                "right_name" => "Список заявок хозяйства",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-05-22 14:10:17.445764",
                "right_log_write" => "disabled",
            ],
            [
                "right_id" => "4",
                "module_slug" => "users",
                "right_action" => "edit",
                "right_name" => "Редактирование пользователя",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-06-20 08:26:48.130149",
                "right_log_write" => "enabled",
            ],
            [
                "right_id" => "5",
                "module_slug" => "users",
                "right_action" => "password_change",
                "right_name" => "Смена пароля",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-06-20 08:26:48.131536",
                "right_log_write" => "enabled",
            ],
            [
                "right_id" => "6",
                "module_slug" => "users",
                "right_action" => "delete",
                "right_name" => "Удаление       пользователя",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-06-20 08:26:48.132918",
                "right_log_write" => "enabled",
            ],
            [
                "right_id" => "7",
                "module_slug" => "users",
                "right_action" => "status",
                "right_name" => "Статус         пользователя",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-06-20 08:26:48.134316",
                "right_log_write" => "enabled",
            ],
            [
                "right_id" => "9",
                "module_slug" => "users",
                "right_action" => "company_add",
                "right_name" => "Установка      компании            пользователя",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-06-20 08:26:48.135731",
                "right_log_write" => "enabled",
            ],
            [
                "right_id" => "11",
                "module_slug" => "users",
                "right_action" => "role_add",
                "right_name" => "Установка      роли            пользователя",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-06-20 08:26:48.13852",
                "right_log_write" => "enabled",
            ],
            [
                "right_id" => "12",
                "module_slug" => "users",
                "right_action" => "role_delete",
                "right_name" => "Удаление       роли            пользователя",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-06-20 08:26:48.142195",
                "right_log_write" => "enabled",
            ],
            [
                "right_id" => "15",
                "module_slug" => "users",
                "right_action" => "location_add",
                "right_name" => "Установка области\района",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-06-20 08:26:48.143648",
                "right_log_write" => "enabled",
            ],
            [
                "right_id" => "16",
                "module_slug" => "users",
                "right_action" => "location_delete",
                "right_name" => "Удаление области\района",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-06-20 08:26:48.145044",
                "right_log_write" => "enabled",
            ],
            [
                "right_id" => "17",
                "module_slug" => "users",
                "right_action" => "herriot_req_add",
                "right_name" => "Добавление реквизитов хорриота",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-06-20 08:26:48.146417",
                "right_log_write" => "enabled",
            ],
            [
                "right_id" => "18",
                "module_slug" => "users",
                "right_action" => "send_requisites",
                "right_name" => "Отправка пользователю реквизитов входа",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-06-20 08:26:48.147797",
                "right_log_write" => "enabled",
            ],
            [
                "right_id" => "22",
                "module_slug" => "roles",
                "right_action" => "create",
                "right_name" => "Добавление     роли",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-06-20 08:26:48.149332",
                "right_log_write" => "enabled",
            ],
            [
                "right_id" => "23",
                "module_slug" => "roles",
                "right_action" => "edit",
                "right_name" => "Редактирование роли",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-06-20 08:26:48.150996",
                "right_log_write" => "enabled",
            ],
            [
                "right_id" => "24",
                "module_slug" => "roles",
                "right_action" => "delete",
                "right_name" => "Удаление       роли",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-06-20 08:26:48.152615",
                "right_log_write" => "enabled",
            ],
            [
                "right_id" => "25",
                "module_slug" => "roles",
                "right_action" => "status",
                "right_name" => "Статус         роли",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-06-20 08:26:48.154026",
                "right_log_write" => "enabled",
            ],
            [
                "right_id" => "27",
                "module_slug" => "roles",
                "right_action" => "right_add",
                "right_name" => "Добавление     права           роли",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-06-20 08:26:48.15546",
                "right_log_write" => "enabled",
            ],
            [
                "right_id" => "28",
                "module_slug" => "roles",
                "right_action" => "right_delete",
                "right_name" => "Удаление       права           роли",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-06-20 08:26:48.156873",
                "right_log_write" => "enabled",
            ],
            [
                "right_id" => "33",
                "module_slug" => "auth",
                "right_action" => "install",
                "right_name" => "Переустановка системы",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-06-20 08:26:48.158429",
                "right_log_write" => "enabled",
            ],
            [
                "right_id" => "34",
                "module_slug" => "auth",
                "right_action" => "migrate",
                "right_name" => "Накатывание миграций",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-06-20 08:26:48.159787",
                "right_log_write" => "enabled",
            ],
            [
                "right_id" => "37",
                "module_slug" => "companies",
                "right_action" => "create",
                "right_name" => "Создать        хозяйство",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-06-20 08:26:48.161177",
                "right_log_write" => "enabled",
            ],
            [
                "right_id" => "38",
                "module_slug" => "companies",
                "right_action" => "status",
                "right_name" => "Статус         хозяйства",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-06-20 08:26:48.162553",
                "right_log_write" => "enabled",
            ],
            [
                "right_id" => "40",
                "module_slug" => "companies",
                "right_action" => "edit",
                "right_name" => "Редактирование хозяйства",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-06-20 08:26:48.16559",
                "right_log_write" => "enabled",
            ],
            [
                "right_id" => "41",
                "module_slug" => "companies",
                "right_action" => "location_add",
                "right_name" => "Установка области\района",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-06-20 08:26:48.167147",
                "right_log_write" => "enabled",
            ],
            [
                "right_id" => "42",
                "module_slug" => "companies",
                "right_action" => "location_delete",
                "right_name" => "Удаление области\района",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-06-20 08:26:48.168545",
                "right_log_write" => "enabled",
            ],
            [
                "right_id" => "64",
                "module_slug" => "applications",
                "right_action" => "data",
                "right_name" => "Полная информация по заявке",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-05-22 14:10:17.445764",
                "right_log_write" => "disabled",
            ],
            [
                "right_id" => "68",
                "module_slug" => "animals",
                "right_action" => "list",
                "right_name" => "Список животных",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-05-22 14:10:17.445764",
                "right_log_write" => "disabled",
            ],
            [
                "right_id" => "69",
                "module_slug" => "animals",
                "right_action" => "data",
                "right_name" => "Полная информация по животному",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-05-22 14:10:17.445764",
                "right_log_write" => "disabled",
            ],
            [
                "right_id" => "75",
                "module_slug" => "selex",
                "right_action" => "login",
                "right_name" => "Авторизация пользователя Селекс",
                "right_slug" => "public",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-05-22 14:10:17.445764",
                "right_log_write" => "disabled",
            ],
            [
                "right_id" => "76",
                "module_slug" => "selex",
                "right_action" => "send_animals",
                "right_name" => "Передача данных по животным",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-05-22 14:10:17.445764",
                "right_log_write" => "disabled",
            ],
            [
                "right_id" => "77",
                "module_slug" => "selex",
                "right_action" => "get_animals",
                "right_name" => "Получение данных по животным",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-05-22 14:10:17.445764",
                "right_log_write" => "disabled",
            ],
            [
                "right_id" => "78",
                "module_slug" => "selex",
                "right_action" => "send_animals",
                "right_name" => "Подтверждение получения данных по животным",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-05-22 14:10:17.445764",
                "right_log_write" => "disabled",
            ],
            [
                "right_id" => "3",
                "module_slug" => "users",
                "right_action" => "create",
                "right_name" => "Создание       пользователя",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-06-20 08:26:48.128301",
                "right_log_write" => "enabled",
            ],
            [
                "right_id" => "10",
                "module_slug" => "users",
                "right_action" => "company_delete",
                "right_name" => "Удаление       компании            пользователя",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-06-20 08:26:48.13712",
                "right_log_write" => "enabled",
            ],
            [
                "right_id" => "39",
                "module_slug" => "companies",
                "right_action" => "delete",
                "right_name" => "Удаление       хозяйства",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-06-20 08:26:48.16395",
                "right_log_write" => "enabled",
            ],
            [
                "right_id" => "65",
                "module_slug" => "applications",
                "right_action" => "animal_add",
                "right_name" => "Добавление животного в заявку",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-06-20 08:26:48.170379",
                "right_log_write" => "enabled",
            ],
            [
                "right_id" => "66",
                "module_slug" => "applications",
                "right_action" => "status",
                "right_name" => "Изменение статуса заявки",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-06-20 08:26:48.171827",
                "right_log_write" => "enabled",
            ],
            [
                "right_id" => "67",
                "module_slug" => "applications",
                "right_action" => "animal_delete",
                "right_name" => "Удаление животного из заявки",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-06-20 08:26:48.173298",
                "right_log_write" => "enabled",
            ],
            [
                "right_id" => "70",
                "module_slug" => "animals",
                "right_action" => "mark_edit",
                "right_name" => "Редактирование средства маркирования",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-06-20 08:26:48.17511",
                "right_log_write" => "enabled",
            ],
            [
                "right_id" => "71",
                "module_slug" => "animals",
                "right_action" => "mark_photo_edit",
                "right_name" => "Редактирование фотографии средства маркирования",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-06-20 08:26:48.176549",
                "right_log_write" => "enabled",
            ],
            [
                "right_id" => "72",
                "module_slug" => "animals",
                "right_action" => "mark_photo_delete",
                "right_name" => "Удаление фотографии средства маркирования",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-06-20 08:26:48.178322",
                "right_log_write" => "enabled",
            ],
            [
                "right_id" => "73",
                "module_slug" => "animals",
                "right_action" => "animal_keeping_object_edit",
                "right_name" => "Редактирование объекта содержания животного",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-06-20 08:26:48.179752",
                "right_log_write" => "enabled",
            ],
            [
                "right_id" => "74",
                "module_slug" => "animals",
                "right_action" => "animal_birth_object_edit",
                "right_name" => "Редактирование объекта рождения животного",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_created_at" => "2024-05-22 14:10:17.445764",
                "update_at" => "2024-06-20 08:26:48.181217",
                "right_log_write" => "enabled",
            ],
            [
                "right_id" => "79",
                "module_slug" => "auth",
                "right_action" => "herriot_error_check",
                "right_name" => "Запуск проверки неизвестных ошибок из хорриота",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_created_at" => "2024-06-25 08:01:02.833785",
                "update_at" => "2024-06-25 08:01:02.833785",
                "right_log_write" => "disabled",
            ],
            [
                "right_id" => "80",
                "module_slug" => "dashboards",
                "right_action" => "average_registration_time_by_day",
                "right_name" => "Среднее время регистрации по дням",
                "right_slug" => "public",
                "right_content_type" => "json",
                "right_created_at" => "2024-07-04 07:54:46.732584",
                "update_at" => "2024-07-04 07:54:46.732584",
                "right_log_write" => "disabled",
            ],
            [
                "right_id" => "81",
                "module_slug" => "dashboards",
                "right_action" => "animal_registration_count_by_day",
                "right_name" => "Количество зарегистрированных животных по дням",
                "right_slug" => "public",
                "right_content_type" => "json",
                "right_created_at" => "2024-07-04 07:54:46.732584",
                "update_at" => "2024-07-04 07:54:46.732584",
                "right_log_write" => "disabled",
            ],
            [
                "right_id" => "82",
                "module_slug" => "dashboards",
                "right_action" => "animal_add_count_by_day",
                "right_name" => "Количество добавленных животных по дням",
                "right_slug" => "public",
                "right_content_type" => "json",
                "right_created_at" => "2024-07-04 07:54:46.732584",
                "update_at" => "2024-07-04 07:54:46.732584",
                "right_log_write" => "disabled",
            ],
            [
                "right_id" => "83",
                "module_slug" => "auth",
                "right_action" => "clean_company_animals",
                "right_name" => "Очистка животных компании",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_created_at" => "2024-07-11 15:53:07.935167",
                "update_at" => "2024-07-11 15:53:07.935167",
                "right_log_write" => "disabled",
            ],
            [
                "right_id" => "84",
                "module_slug" => "animals",
                "right_action" => "mark_edit_group",
                "right_name" => "Групповое редактирование средства маркирования",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_created_at" => "2024-07-22 16:49:05.103919",
                "update_at" => "2024-07-22 16:49:05.103919",
                "right_log_write" => "disabled",
            ],
            [
                "right_id" => "85",
                "module_slug" => "animals",
                "right_action" => "animal_object_edit_group",
                "right_name" => "Групповое редактирование места рождения, содержания, типа и вида содержания",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_created_at" => "2024-07-29 07:52:45.377793",
                "update_at" => "2024-07-29 07:52:45.377793",
                "right_log_write" => "disabled",
            ],
            [
                "right_id" => "86",
                "module_slug" => "companies",
                "right_action" => "set_company_objects_favorite",
                "right_name" => "Установка поднадзорных объектов в избранное",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_created_at" => "2024-07-29 07:52:45.596865",
                "update_at" => "2024-07-29 07:52:45.596865",
                "right_log_write" => "disabled",
            ],
            [
                "right_id" => "87",
                "module_slug" => "companies",
                "right_action" => "unset_company_objects_favorite",
                "right_name" => "Удаление поднадзорных объектов из избранного",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_created_at" => "2024-07-29 07:52:45.596865",
                "update_at" => "2024-07-29 07:52:45.596865",
                "right_log_write" => "disabled",
            ],
            [
                "right_id" => "88",
                "module_slug" => "animals",
                "right_action" => "animal_keeping_purpose_edit",
                "right_name" => "Редактирование целей содержания",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_created_at" => "2024-07-29 07:52:45.598824",
                "update_at" => "2024-07-29 07:52:45.598824",
                "right_log_write" => "disabled",
            ],
            [
                "right_id" => "89",
                "module_slug" => "animals",
                "right_action" => "animal_keeping_type_edit",
                "right_name" => "Редактирование видов содержания",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_created_at" => "2024-07-29 07:52:45.598824",
                "update_at" => "2024-07-29 07:52:45.598824",
                "right_log_write" => "disabled",
            ],
        ]);
    }
}
